name: ocaviva
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  intl: ^0.15.2
  cloud_firestore: ^0.13.2+3
  firebase_core: ^0.4.0  # add dependency for Firebase Core
  firebase_analytics: ^1.0.4  # add dependency for Google Analytics for Firebase
  firebase_database: ^3.0.7
  firebase_auth: ^0.14.0+5
  flutter:
    sdk: flutter
  rflutter_alert: ^1.0.2
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.2.0
  flutter_offline: "^0.3.0"
  connectivity: ^0.4.8+2
  random_color: ^1.0.5

  #rflutter_alert:
  #  git: git://github.com/RatelHub/rflutter_alert.git


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  mobx: ^0.3.8
  flutter_mobx: ^0.3.3
  shared_preferences: ^0.5.3+4
  google_fonts: ^0.3.5
  json_annotation: ^2.2.0
  pie_chart: 1.3.0
  charts_flutter: ^0.4.0
  charts_common: ^0.4.0
  flutter_circular_chart: ^0.1.0
  webview_flutter: ^0.3.19
  
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.0
  mobx_codegen: ^0.3.3+1
  json_serializable: ^2.2.0
  hive_generator: ^0.7.0+2

  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - assets/images/oca_viva-logo.png
  - assets/images/digestorio.png
  - assets/images/circulatorio.png
  - assets/images/esqueletico.png
  - assets/images/muscular.png
  - assets/images/nervoso.png
  - assets/images/fundo-1.png
  - assets/jogo.json
  - assets/users.json
  - assets/images/fase_1/desafio_1.png
  - assets/images/fase_1/desafio_2.png
  - assets/images/fase_1/desafio_3.png
  - assets/images/fase_1/desafio_.png
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages